FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache git

# Pre-copy/cache go.mod for pre-downloading dependencies
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Command to run when starting the container
CMD ["go", "run", "cmd/api/main.go"] 